environment = "dev"
region = "us-east-1"
s3_bucket = "davron-terraform-eks"              #Will be used to set backend.tf
s3_folder_project = "application"            #Will be used to set backend.tf
s3_folder_region = "us-east-1"               #Will be used to set backend.tf
s3_folder_type = "state"                     #Will be used to set backend.tf
s3_tfstate_file = "infra.tfstate.json"   #Will be used to set backend.tf
vpc_id = "vpc-04fb44225020a577d"
subnet1 = "subnet-057f87b537421d655"
subnet2 = "subnet-08ea3f206183770b3"
subnet3 = "subnet-03c00639bfc9193a0"
cluster_name = "my-cluster"
instance_type = "t2.micro"
asg_max_size = "48" 
asg_min_size = "3"
asg_desired_capacity = "3"
cluster_version = "1.14"
